apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microservice
  labels:
    app: users-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-microservice
  template:
    metadata:
      labels:
        app: users-microservice
    spec:
      containers:
      - name: users-microservice
        image: 359197523982.dkr.ecr.us-east-2.amazonaws.com/users-microservice:latest
        ports:
        - containerPort: 80
