apiVersion: v1
kind: Service
metadata:
  name: users-microservice
spec:
  selector:
    app.kubernetes.io/name: users-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer